package cn.hui.vote.dal.domain;

import lombok.Data;

/**
 * VoteContentDO 
 *
 * @author Auto generated by luzhaohui
 * @since 2020-03-16
 * @version 1.0
 */
@Data
public class VoteContentDO extends BaseBean {

    private static final long serialVersionUID = -1L;


    /**
    * form_id
    */
    private Long formId;

    /**
    * line_num
    */
    private Integer lineNum;

    /**
    * line_text
    */
    private String lineText;

    /**
    * line_pic
    */
    private String linePic;

}
