package cn.hui.vote.dal.domain;

import lombok.Data;

/**
 * VoteRecordDO 
 *
 * @author Auto generated by luzhaohui
 * @since 2020-03-16
 * @version 1.0
 */
@Data
public class VoteRecordDO extends BaseBean {

    private static final long serialVersionUID = -1L;


    /**
    * user_id
    */
    private Long userId;

    /**
    * form_id
    */
    private Long formId;

    /**
    * vote
    */
    private String vote;

}
