package cn.hui.vote.domain;

import lombok.Data;

import java.util.Date;

/**
 * VoteFormDO 
 *
 * @author Auto generated by luzhaohui
 * @since 2020-03-16
 * @version 1.0
 */
@Data
public class VoteFormBO {

    private static final long serialVersionUID = -1L;

    private Long    id;
    private Date gmtCreate;
    private Date    gmtModify;
    /**
    * vote_name
    */
    private String voteName;

    /**
    * creator_weibo_id
    */
    private Long creatorWeiboId;

    private Integer multiVote;
}
