package cn.hui.vote.dal.mapper;

import cn.hui.vote.dal.domain.VoteRecordDO;

/**
 * VoteRecordMapper
 *
 * @author Auto generated by luzhaohui
 * @since 2020-03-16
 * @version 1.0
 */
public interface VoteRecordMapper extends BaseMapper<VoteRecordDO> {

    // custom method

}