package cn.hui.vote.dal.mapper;

import cn.hui.vote.dal.domain.VoteFormDO;

import java.util.List;

/**
 * VoteFormMapper
 *
 * @author Auto generated by luzhaohui
 * @since 2020-03-16
 * @version 1.0
 */
public interface VoteFormMapper extends BaseMapper<VoteFormDO> {

    // custom method
    List<VoteFormDO> selectAll();
}